// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_clima.Data;

#nullable disable

namespace web_clima.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240902181901_UpdateUserModel")]
    partial class UpdateUserModel
    {
        // Remova a tentativa de sobrescrita do método BuildTargetModel
    }
}
